### ISSUE TITLE
Bone meal is used when sapling is not able to grow

### ISSUE THREAD

**Issue by LucasPMagno** [GameModsBR/MineCity#57]
Using Forge 1.7.10 with NEI, NEIIntegration, Translocator, EnderStorage, CodeChickenCore, CodeChickenLib and ForgeMultiPart. On survival mode, bone meal is used while trying to grow a sapling and after using enough to make the sapling grow it keeps using the bone meal and saying "You don't have permission to perform this action."
My suggestion is to check if upon growth it would grief a city (or nature) nearby and if it would don't allow the use of bonemeal. That is just my suggestion I don't know how feasible that would be.

**Comment by joserobjr** [comment]
Was the sapling in an unmodifiable location? If the sapling was modifiable (we can break and replant the sapling) then it's correct to waste bone meal on unsuccessful grows.

> My suggestion is to check if upon growth it would grief a city (or nature) nearby and if it would don't allow the use of bonemeal.
There's no way to predict which blocks will be changed because it's based on random generators and because other mods can create new type of trees that grows differently from vanilla Minecraft, so to handle that we mark the world to capture snapshots of changed blocks, let the the plant grow and check if it grew to an unauthorized location, if it did it then we revert all changes. The vanilla behaviour of bone meal is to waste it on unsuccessful attempts to grow.

**Comment by LucasPMagno** [comment]
> Was the sapling in an unmodifiable location? If the sapling was modifiable (we can break and replant the sapling) then it's correct to waste bone meal on unsuccessful grows.

It was on modifiable location.
