### ISSUE TITLE
City Map with offset

### ISSUE THREAD

**Issue by ETblaky** [GameModsBR/MineCity#74]
The city map seens to have an offset of some squares to the left.

![2016-11-13_19 30 51](https://cloud.githubusercontent.com/assets/9395746/20249064/5fc1c036-a9d8-11e6-95b0-9e5b10f497e7.png)

*The Orange square is the ETLandia city, wich is shown when the mouse is over some squares to the left.

**Comment by joserobjr** [comment]
This bug is caused by [https://github.com/MinecraftForge/MinecraftForge](Minecraft Forge) itself, forge is changing the chat rendering logic and is causing the issue.

Unfortunately there's no way to fix from here because MineCity is a server-side mod, however this could be fixed from an optional client mod that I'm planning to create.
